smart_dog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('smart_dogs.urls')),
]

smart_dogs/urls.py
"""Define URL patterns for smart_dogs."""

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'smart_dogs'
urlpatterns = [
    # Main page
    path('', views.index, name='index'),
    # Courses page
    path('courses/', views.courses, name='courses'),
    # Add course
    path('new_course/', views.new_course, name='new_course'),
    # About course
    path('courses/<int:course_id>/', views.about_course, name='about_course'),

    # Forum page
    path('forum/', views.forum, name='forum'),
    # Add new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Topic page
    path('forum/<int:topic_id>/', views.topic, name='topic'),
    # Add entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Edit entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # Feedbacks page
    path('feedbacks/', views.feedbacks, name='feedbacks'),
    # Add feedback
    path('new_feedback/', views.new_feedback, name='new_feedback'),
    # Edit feedback
    path('edit_feedback/<int:feedback_id>/', views.edit_feedback, name='edit_feedback'),
    # Cooperation page
    path('cooperation/', views.cooperation, name='cooperation'),
    # Authentication Page - Login or Registration page
    path('authentication/', views.authentication, name='authentication'),

    # User home page with courses
    path('user_courses/', views.user_courses, name='user_courses'),

    path('register_course/<int:course_id>/', views.register_course, name='register_course'),

    path('about_user_course/<int:course_id>/', views.about_user_course, name='about_user_course'),

    path('section_detail/<int:section_id>/', views.section_detail, name='section_detail'),
    
    # Quiz
    path('dog_quiz/', views.dog_quiz, name='dog_quiz'),
    path('success_page/<int:course_id>/', views.success_page, name='success_page'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Define URL patterns for users."""

from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # Add authentication URL
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

smart_dogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """The topic the user is discussing in forum."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Some specific information on this topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.text[:50]}..."

class Feedback(models.Model):
    """Feedback."""
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    # date_added = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'feedbacks'

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.text[:50]}..."


class Course(models.Model):
    """Course name."""
    text = models.CharField(max_length=200)
    image = models.ImageField(upload_to='smart_dogs/templates/smart_dogs/course_images/', null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

    
class CourseModule(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    number = models.PositiveIntegerField()  # Номер модуля
    title = models.CharField(max_length=200)

    def __str__(self):
        return f"Модуль {self.number}: {self.title}"

class ModuleSection(models.Model):
    module = models.ForeignKey(CourseModule, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()

    def __str__(self):
        return f"Розділ: {self.title}"


class About_course(models.Model):
    """About course"""
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    # New fields
    phrase = models.CharField(max_length=200, default='Default Phrase')
    course_description = models.TextField(default='Default Course Description')
    target_audience = models.CharField(max_length=100, choices=[
        ('beginners', 'Новачки'),
        ('enthusiasts', 'Любителям'),
        ('experts', 'Експертам'),
    ], default='beginners')
    modules = models.ManyToManyField(CourseModule, related_name='about_courses')


    class Meta:
        verbose_name_plural = 'about_courses'

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.phrase[:50]}..."


class RegisteredCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} - {self.course.text}"


class SectionDetail(models.Model):
    section = models.ForeignKey(ModuleSection, on_delete=models.CASCADE)
    text = models.TextField(blank=True, null=True)
    photo = models.ImageField(upload_to='section_photos/', blank=True, null=True)
    video = models.FileField(upload_to='section_videos/', blank=True, null=True)

    def __str__(self):
        return f'Detail for Section {self.section.title}'


class DogQuiz(models.Model):
    name = models.CharField(max_length=255)
    age = models.IntegerField()
    size = models.CharField(max_length=50, choices=[
        ('small', 'Маленька'),
        ('medium', 'Середня'),
        ('large', 'Велика'),
    ])
    skill_level = models.CharField(max_length=50, choices=[
        ('beginner', 'Новачок'),
        ('intermediate', 'Любитель'),
        ('professional', 'Професіонал'),
    ])

    def __str__(self):
        return self.name

smart_dogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _
# from django.utils.translation import activate

from .models import Topic, Feedback, Course, Entry, About_course, CourseModule, RegisteredCourse, ModuleSection, DogQuiz 
from .forms import TopicForm, EntryForm, CourseForm, FeedbackForm, DogQuizForm


from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from django.utils.safestring import SafeText

# activate("uk")

# Create your views here.
def index(request):
    """Main page"""
    return render(request, 'smart_dogs/index.html')

def courses(request):
    """Courses page"""
    courses = Course.objects.order_by('date_added')
    context = {'courses': courses}
    return render(request, 'smart_dogs/courses.html', context)

@login_required
def new_course(request):
    """Add a new course."""
    if request.method != 'POST':
        # No data sent. Create an empty form.
        form = CourseForm()
    else:
        # Sent POST; process the data.
        form = CourseForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('smart_dogs:courses')
        
    # Show empty or invalid form.
    context = {'form': form}
    return render(request, 'smart_dogs/new_course.html', context)


def about_course(request, course_id):
    """About course page"""
    course = Course.objects.get(id=course_id)
    about_course_set = course.about_course_set.all()
    modules = CourseModule.objects.filter(course=course)
    context = {'course': course, 'about_course_set': about_course_set, 'modules': modules}
    return render(request, 'smart_dogs/about_course.html', context)



def forum(request):
    """Forum page"""
    # Display all topics
    forum = Topic.objects.order_by('date_added')
    context = {'forum': forum}
    return render(request, 'smart_dogs/forum.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data sent. Create an empty form.
        form = TopicForm()
    else:
        # Sent POST; process the data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('smart_dogs:forum')
        
    # Show empty or invalid form.
    context = {'form': form}
    return render(request, 'smart_dogs/new_topic.html', context)


def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'smart_dogs/topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # No data sent. Create an empty form.
        form = EntryForm()
    else:
        # Sent POST; process the data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user  
            new_entry.save()
            return redirect('smart_dogs:topic', topic_id=topic_id)
        
    # Show empty or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'smart_dogs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
 
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('smart_dogs:topic', topic_id=topic.id)
        
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'smart_dogs/edit_entry.html', context)
        

def feedbacks(request):
    """Feedbacks page"""
    # Display all feedbacks
    feedbacks = Feedback.objects.order_by('-date_added')
    context = {'feedbacks': feedbacks}
    return render(request, 'smart_dogs/feedbacks.html', context)

@login_required
def new_feedback(request):
    """Add a new feedback."""
    if request.method != 'POST':
        # No data sent. Create an empty form.
        form = FeedbackForm()
    else:
        # Sent POST; process the data.
        form = FeedbackForm(data=request.POST)
        if form.is_valid():
            new_feedback = form.save(commit=False)
            new_feedback.owner = request.user  
            new_feedback.save()
            return redirect('smart_dogs:feedbacks')
        
    # Show empty or invalid form.
    context = {'form': form}
    return render(request, 'smart_dogs/new_feedback.html', context)


@login_required
def edit_feedback(request, feedback_id):
    """Edit an existing feedback."""
    feedback = Feedback.objects.get(id=feedback_id)
 
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = FeedbackForm(instance=feedback)
    else:
        # POST data submitted; process data.
        form = FeedbackForm(instance=feedback, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('smart_dogs:feedbacks')
        
    context = {'feedback': feedback, 'form': form}
    return render(request, 'smart_dogs/edit_feedback.html', context)


def cooperation(request):
    """Cooperation page"""
    return render(request, 'smart_dogs/cooperation.html')

def authentication(request):
    """Authentication page"""
    return render(request, 'smart_dogs/authentication.html')

def user_courses(request):
    """User courses page"""
    return render(request, 'smart_dogs/user_courses.html')

# from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

@login_required
def register_course(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    
    # Перевірка, чи користувач ще не зареєстрований на цей курс
    if not RegisteredCourse.objects.filter(user=request.user, course=course).exists():
        RegisteredCourse.objects.create(user=request.user, course=course)

    return redirect('smart_dogs:user_courses')

from django.shortcuts import render
from .models import RegisteredCourse

@login_required
def user_courses(request):
    # Отримати курси, на які користувач зареєстрований
    user_courses = RegisteredCourse.objects.filter(user=request.user).select_related('course')

    context = {'user_courses': user_courses}
    return render(request, 'smart_dogs/user_courses.html', context)


def about_user_course(request, course_id):
    """About user's course page"""
    course = Course.objects.get(id=course_id)
    modules = CourseModule.objects.filter(course=course)
    context = {'user': request.user, 'course': course, 'modules': modules}
    return render(request, 'smart_dogs/about_user_course.html', context)

@login_required
def section_detail(request, section_id):
    section = get_object_or_404(ModuleSection, id=section_id)

    registered_course = get_object_or_404(RegisteredCourse, user=request.user, course=section.module.course)

    # Отримайте попередній і наступний розділ
    previous_section = ModuleSection.objects.filter(module=section.module, id__lt=section_id).order_by('-id').first()
    next_section = ModuleSection.objects.filter(module=section.module, id__gt=section_id).order_by('id').first()

    context = {'section': section, 'previous_section': previous_section, 'next_section': next_section, 'course_id': registered_course.course.id}
    return render(request, 'smart_dogs/section_detail.html', context)

def success_page(request):
    return render(request, 'smart_dogs/success_page.html')

@login_required
def dog_quiz(request):
    if request.method == 'POST':
        form = DogQuizForm(request.POST)
        if form.is_valid():
            form.save()
            recommended_course = analyze_user_responses(form.cleaned_data)
            if recommended_course:
                return render(request, 'smart_dogs/dog_quiz.html', {'form': form, 'recommended_course': recommended_course})
            else:
                return render(request, 'smart_dogs/dog_quiz.html', {'form': form, 'no_course_found': True})
    else:
        form = DogQuizForm()
    
    return render(request, 'smart_dogs/dog_quiz.html', {'form': form})


import random

def analyze_user_responses(form_data):
    # Отримання рівня підготовки користувача
    user_level = form_data.get('skill_level')

    # Перевірка, чи отримано значення рівня підготовки користувача з форми
    if user_level is not None:
        user_level = user_level.lower()
    else:
        return "Рівень підготовки користувача не визначено"

    # Отримання всіх описів курсів та їх цільової аудиторії
    courses_info = About_course.objects.all()

    # Ініціалізація змінних для збереження найкращого курсу та його схожості з користувачем
    best_courses = []
    best_similarity = -1

    # Проходження по кожному курсу
    for course_info in courses_info:
        # Перевірка для рівня навичок "Новачок"
        if user_level == 'beginner':
            if 'beginners' in course_info.target_audience.lower():
                # Обчислення схожості
                vectorizer = CountVectorizer().fit_transform([str(form_data[field_name]) for field_name in form_data] + [course_info.course_description])
                similarity_matrix = cosine_similarity(vectorizer)
                similarity = similarity_matrix[0][-1]

smart_dogs/templates/smart_dogs/about_user_course.html
<!-- about_user_course.html -->
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
    <link rel="stylesheet" href="{% static 'about_user_course.css' %}">
{% endblock links %}



{% block content %}
    <div class="line"></div>


    <div class="intro">
        <h2>Вітаємо, {{ user.username }} на курсі "{{ course.text }}"!</h2>

        <!-- Відображення модулів та розділів -->
        <h3>Програма курсу:</h3>
        {% for module in modules %}
            <h4>{{ module }}</h4>
            <ul>
                {% for section in module.modulesection_set.all %}
                    <li>
                        <a href="{% url 'smart_dogs:section_detail' section.id %}">{{ section.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </div>

    <div class="line"></div>

{% endblock content %}

smart_dogs/templates/smart_dogs/authentication.html
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
    <link rel="stylesheet" href="{% static 'authentication.css' %}">
{% endblock links %}


{% block content %}

    <div class="line"></div>  

    <div class="auth">
        <div class="offers_h5">
            <a href="{% url 'users:register' %}">РЕЄСТРАЦІЯ</a>
        </div>

        <div class="dog_auth"></div>

        <div class="offers_h5">
            <a href="{% url 'users:login' %}">ВХІД</a>
        </div>
    </div>
{% endblock content %}

smart_dogs/templates/smart_dogs/cooperation.html
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
    <link rel="stylesheet" href="{% static 'cooperation.css' %}">
{% endblock links %}

{% block content %}
    <div class="main_photo_cooperation">
        <h2>наша мiсiя - зробити навчання доступним i цiкавим для кожного</h2>
    </div>

    <div class="advantages">
        <h4 class="h4_white">НАШI ПЕРЕВАГИ:</h4>

        <div class="adv_div">
            <div class="adv">
                <h5 class="h5_white">доступність освiти</h5>
                <p class="p_white">Ми дбаємо про те, щоб кожна людина мала можливість навчатися, будь-де та будь-коли</p>
            </div>
            <div class="adv"> 
                <h5 class="h5_white">Навчання українською</h5>
                <p class="p_white">Проблема сьогодення - брак або повна відсутність якісних навчальних ресурсів українською. Ми взяли на себе удар це змінити</p>
            </div>
            <div class="adv">
                <h5 class="h5_white">якiсть навчання</h5>
                <p class="p_white">Відгуки наших учнів говорять про те, наскільки для нас важлива якість нашого продукту</p>
            </div>
        </div>

    </div>

    <div class="part">
        <h4>Нашi партнери:</h4>
        <p>Зовсім скоро тут з’являться лого наших перших партнерів</p>
        <div class="partners">

            <div class="left_paw"></div>
            <div class="partner1"></div>
            <div class="partner2"></div>
            <div class="partner3"></div>
            <div class="partner4"></div>
            <div class="right_paw"></div>

        </div>
    </div>

{% endblock content %}

smart_dogs/templates/smart_dogs/dog_quiz.html
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
    <link rel="stylesheet" href="{% static 'user_courses.css' %}">
{% endblock links %}

{% block content %}

    <div class="line"></div>

    <div class="navs">
        <nav>
            <h3 class="h3-nav">Ваші можливості</h3>
            <a href="{% url 'smart_dogs:user_courses' %}" class="a-nav">ваші курси</a>
            <a href="{% url 'smart_dogs:dog_quiz' %}" class="a-nav">підібрати курс</a>
            
        </nav>


        <div class="nav-courses">
            <h1 class="h3-nav">Опитування про вашу собаку</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="l_button">подати</button>
            </form>


            {% if recommended_course %}
                <h2>Рекомендований курс:</h2>
                <p>{{ recommended_course }}</p>
            {% elif no_course_found %}
                <p>Рекомендований курс не знайдено. Будь ласка, спробуйте ще раз або зв'яжіться з адміністратором.</p>
            {% endif %}
        </div>
    </div>

    <div class="line"></div>

{% endblock content %}

smart_dogs/templates/smart_dogs/edit_entry.html
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
  <link rel="stylesheet" href="{% static 'new_entry.css' %}">
{% endblock links %}

{% block content %}
  <div class="line"></div>  

  <h2>Відредагуйте пост:</h2>

  <form action="{% url 'smart_dogs:edit_entry' entry.id %}" method='post' class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" class="button">зберегти зміни</button>
  </form>

{% endblock content %}
    

smart_dogs/templates/smart_dogs/feedbacks.html
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
    <link rel="stylesheet" href="{% static 'feedbacks.css' %}">
{% endblock links %}

{% block content %}
    <div class="main_photo_feedbacks">
        <h2>Відгуки</h2>
    </div>


    <div class="newpost">
        {% if user.is_authenticated %}
            <div class="main_button2">
                <a href="{% url 'smart_dogs:new_feedback' %}">додати новий відгук</a>
            </div>
        {% else %}
            <p class="p_feedback2">
                Щоб додати новий відгук 
                <a href="{% url 'smart_dogs:authentication' %}" class="p_feedback2">увійдіть</a>.
            </p>
        {% endif %}


        <div class="feedbacks">
            {% for feedback in feedbacks %}
                <div class="feedback">
                    <p class="p_feedback2">{{ feedback.date_added|date:'d.m.Y H:i' }} - {{ feedback.owner.username }}</p>
                    <p class="p_feedback">{{ feedback.text|linebreaks }}</p>

                    {% if feedback.owner == user %}
                        <a href="{% url 'smart_dogs:edit_feedback' feedback.id %}" class="p_feedback2">редагувати</a>
                    {% endif %}

                    </div> 
            {% empty %}
                <p class="p_feedback2">Жодного відгуку не було додано.</p>
            {% endfor %}


        </div>

    </div>

{% endblock content %}

smart_dogs/templates/smart_dogs/forum.html
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
    <link rel="stylesheet" href="{% static 'forum.css' %}">
{% endblock links %}

{% block content %}
    <div class="fm">
        <div class="main_photo_forum">
            <h2>Ласкаво просимо</h2>
            <h2>на наш форум!</h2>
        </div>

        <div class="forum">
            <h5>Тут ви знайдете розділи для обговорення найрізноманітніших тем. Ми створили велику бібліотеку статей, які охоплюють усі аспекти кінології та дресирування собак. Розділіть свої думки, досвід та питання з іншими учасниками спільноти. Разом ми можемо зробити кожного власника щасливішим та собак краще навченими!"</p>
            <h4>Теми для ОБГОВОРЕННЯ:</h4>
            
            <div class="topic">
                <ul>
                    {% for topic in forum %}
                        <li>
                            <a href="{% url 'smart_dogs:topic' topic.id %}">{{ topic }}</a>
                        </li>
                    {% empty %}
                        <li>Жодної теми не було додано.</li>
                    {% endfor %}
                </ul>
            </div>

            
        </div>
        

        <div class="button2"><a href="{% url 'smart_dogs:new_topic' %}" class="main_button2">додати тему</a></div>
    </div>
        
{% endblock content %}

smart_dogs/templates/smart_dogs/new_course.html
{% extends "smart_dogs/base.html" %}
{% load i18n %}


{% block content %}
  <p>Додайте новий курс тут:</p>
    
  <form action="{% url 'smart_dogs:new_course' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Додати курс</button>
  </form>
  
{% endblock content %}

smart_dogs/templates/smart_dogs/new_feedback.html
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
  <link rel="stylesheet" href="{% static 'new_entry.css' %}">
{% endblock links %}

{% block content %}

  <div class="line"></div>  

  <h2>Напишіть новий відгук тут:</h2>
    
  <form action="{% url 'smart_dogs:new_feedback' %}" method='post' class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" class="button">додати відгук</button>
  </form>
    
{% endblock content %}

smart_dogs/templates/smart_dogs/new_topic.html
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
  <link rel="stylesheet" href="{% static 'new_entry.css' %}">
{% endblock links %}

{% block content %}
  <div class="line"></div>  
  <h2>Напишіть ідею нової теми для обговорення тут:</h2>
    
  <form action="{% url 'smart_dogs:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" class="button">додати тему</button>
  </form>
    
{% endblock content %}

smart_dogs/templates/smart_dogs/success_page.html
<!DOCTYPE html>
<html>
<head>
    <title>Success Page</title>
</head>
<body>
    {% if recommended_course %}
        <h1>Ура! Вам підходить цей курс!</h1>
        <p>Рекомендований курс: {{ recommended_course }}</p>
        <!-- Інші елементи або інформація, яку ви хочете відобразити -->
    {% else %}
        <h1>Курсу не знайдено</h1>
        <p>Вибачте, рекомендований курс не знайдено.</p>
        <!-- Інші елементи або інформація, яку ви хочете відобразити -->
    {% endif %}
</body>
</html>

smart_dogs/templates/smart_dogs/topic.html
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
    <link rel="stylesheet" href="{% static 'topic.css' %}">
{% endblock links %}



{% block content %}
    <div class="main_photo_topic">
        <h2>{{ topic }}</h2>
    </div>

    <div class="newpost">
        {% if user.is_authenticated %}
            <a href="{% url 'smart_dogs:new_entry' topic.id %}" class="main_button2">додати новий пост</a>

        {% else %}
            <p class="p_entry2">
                Щоб додати новий пост 
                <a href="{% url 'smart_dogs:authentication' %}" class="p_entry2">увійдіть</a>.
            </p>
        {% endif %}
    
    
        <div class="entries">
            {% for entry in entries %}
                <div class="entry">
                    <p class="p_entry2">{{ entry.date_added|date:'d.m.Y H:i' }} - {{ entry.owner.username }}</p>
                    <p class="p_entry">{{ entry.text|linebreaks }}</p>

                    {% if entry.owner == user %}
                        <a href="{% url 'smart_dogs:edit_entry' entry.id %}" class="p_entry2">редагувати</a>
                    {% endif %}

                    </div> 
            {% empty %}
                <p class="p_entry2">Жодного посту не було додано.</p>
            {% endfor %}


        </div>
    </div>


{% endblock content %}

smart_dogs/templates/smart_dogs/user_courses.html
{% extends "smart_dogs/base.html" %}
{% load i18n static %}


{% block links %}
    <link rel="stylesheet" href="{% static 'user_courses.css' %}">
{% endblock links %}

{% block content %}
    <div class="line"></div>

    <div class="navs">
        <nav>
            <h3 class="h3-nav">Ваші можливості</h3>
            <a href="{% url 'smart_dogs:user_courses' %}" class="a-nav">ваші курси</a>
            <a href="{% url 'smart_dogs:dog_quiz' %}" class="a-nav">підібрати курс</a>
            
        </nav>

        <div class="nav-courses">
            {% if user_courses %}
                <h2 class="cs">Ваші курси:</h2>
                
                <div class="all_courses">
                    {% for registered_course in user_courses %}
                        <div class="course">
                            {% if registered_course.course.image %}
                                <img src="{{ registered_course.course.image.url }}" alt="{{ registered_course.course.text }}" style="width: 26vw; height: 19vw; object-fit: cover;">
                            {% endif %}
                            
                            <a href="{% url 'smart_dogs:about_user_course' registered_course.course.id %}" class="courses_name">
                                {{ registered_course.course.text }}
                            </a>
                        </div>
                    {% empty %}
                        <p class="courses_name2">Жодного курсу не було додано.</p>
                    {% endfor %}
                </div>

            {% else %}
                <p class="no-courses">В вас поки що немає курсів.</p>
                <p class="no-courses2">Оберіть свій курс <a href="{% url 'smart_dogs:courses' %}" class="no-courses2">тут</a>.</p>
            {% endif %}
        </div>

    </div>



    <div class="line"></div>

{% endblock content %}